### ISSUE TITLE
heroku policy breach

### ISSUE THREAD

**Issue by antanisblinda** [lankybutmacho/web-to-kindle#2]
hi there.
just to let you know that the script apparently violates heroku policies and cannot be deployed anymore :(
i'm not sure if they are notifying old users as well (or if you are still using)
I love the thing you did with your old kindle and i was trying to do the same but didn't work out due to the below :(
I will see if i can manage to have my synology create the png.
thanks!

**Comment by lankybutmacho** [comment]
Thanks for the heads up! Still trying to figure out exactly what in the policy I'm violating. In the meantime, looks like forking the repo was enough to get it working again for now. Try this one: https://github.com/lankybutmacho/web-to-kindle-heroku

**Comment by antanisblinda** [comment]
thank you! I tried the forked one and I'm not getting any error indeed! 
any idea on how to add a delay to the generation of the png? I'm using against dakboard and the png generated shows still the "loading modules" :) I think it may need to wait half a sec or so...
thank you!

**Comment by lankybutmacho** [comment]
Yeah, this is a puppeteer question so it's worth reading the docs, but the most reliable way would be to find an element you expect to be on the page, and then wait for it to be present before taking the screenshot. You'd add a line before the `await page.screenshot()` like this: `await page.waitForSelector("#id-of-your-element");`. Of course selecting it by a class name or other selector would also work.

**Comment by antanisblinda** [comment]
Thank you, I will dive into the docs!
